// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDikFdFp72-fFlplPX7Anj1dShliCJfM-s',
    appId: '1:121947744874:web:290c31215c3f4370c13813',
    messagingSenderId: '121947744874',
    projectId: 'samagra-clone-273d7',
    authDomain: 'samagra-clone-273d7.firebaseapp.com',
    storageBucket: 'samagra-clone-273d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjMUbXAR9lYGguaF5XbhrrrlUrNa2G-yY',
    appId: '1:121947744874:android:97808dd245e9e46cc13813',
    messagingSenderId: '121947744874',
    projectId: 'samagra-clone-273d7',
    storageBucket: 'samagra-clone-273d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG1wUHimvCWkiEqeamdiGe-7lc_o4_C00',
    appId: '1:121947744874:ios:f1d393a2d45141c5c13813',
    messagingSenderId: '121947744874',
    projectId: 'samagra-clone-273d7',
    storageBucket: 'samagra-clone-273d7.firebasestorage.app',
    iosBundleId: 'com.example.samagraClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG1wUHimvCWkiEqeamdiGe-7lc_o4_C00',
    appId: '1:121947744874:ios:f1d393a2d45141c5c13813',
    messagingSenderId: '121947744874',
    projectId: 'samagra-clone-273d7',
    storageBucket: 'samagra-clone-273d7.firebasestorage.app',
    iosBundleId: 'com.example.samagraClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDikFdFp72-fFlplPX7Anj1dShliCJfM-s',
    appId: '1:121947744874:web:7c34bc8b64c7711bc13813',
    messagingSenderId: '121947744874',
    projectId: 'samagra-clone-273d7',
    authDomain: 'samagra-clone-273d7.firebaseapp.com',
    storageBucket: 'samagra-clone-273d7.firebasestorage.app',
  );
}
