// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3HuNUEN2-474o1zFg5R0_jqxPVHlkdmc',
    appId: '1:806256295306:web:a79f07ba8da2fe751e5c73',
    messagingSenderId: '806256295306',
    projectId: 'samagra-clone-50f1c',
    authDomain: 'samagra-clone-50f1c.firebaseapp.com',
    storageBucket: 'samagra-clone-50f1c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTqRtGONboH1BDwiD4UAqrFOHM9aB6w9s',
    appId: '1:806256295306:android:d8b6a6bd1e1aae491e5c73',
    messagingSenderId: '806256295306',
    projectId: 'samagra-clone-50f1c',
    storageBucket: 'samagra-clone-50f1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2OG_MWy1d27YOCY1eqDysTYD_0Kph6Mc',
    appId: '1:806256295306:ios:fc549169686c88b81e5c73',
    messagingSenderId: '806256295306',
    projectId: 'samagra-clone-50f1c',
    storageBucket: 'samagra-clone-50f1c.firebasestorage.app',
    iosBundleId: 'com.example.samagraClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2OG_MWy1d27YOCY1eqDysTYD_0Kph6Mc',
    appId: '1:806256295306:ios:fc549169686c88b81e5c73',
    messagingSenderId: '806256295306',
    projectId: 'samagra-clone-50f1c',
    storageBucket: 'samagra-clone-50f1c.firebasestorage.app',
    iosBundleId: 'com.example.samagraClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3HuNUEN2-474o1zFg5R0_jqxPVHlkdmc',
    appId: '1:806256295306:web:aacab41f261822bc1e5c73',
    messagingSenderId: '806256295306',
    projectId: 'samagra-clone-50f1c',
    authDomain: 'samagra-clone-50f1c.firebaseapp.com',
    storageBucket: 'samagra-clone-50f1c.firebasestorage.app',
  );
}
